--1.
SELECT STUDENT_NO AS 학번, STUDENT_NAME AS 이름, ENTRANCE_DATE AS 입학년도
FROM TB_STUDENT
WHERE DEPARTMENT_NO = '002'
ORDER BY ENTRANCE_DATE;

--2.
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE PROFESSOR_NAME NOT LIKE '___';

--3.
SELECT PROFESSOR_NAME AS 교수이름, 
(EXTRACT(YEAR FROM SYSDATE) 
-EXTRACT(YEAR FROM (TO_DATE (SUBSTR (PROFESSOR_SSN,1,6), 'YYMMDD'))))
+100 AS 나이
FROM TB_PROFESSOR
ORDER BY 나이;

--4.
SELECT SUBSTR(PROFESSOR_NAME,2,2) AS 이름
FROM TB_PROFESSOR;

--5.
SELECT *
FROM (
    SELECT STUDENT_NO, STUDENT_NAME, 
           ABS(EXTRACT(YEAR FROM ENTRANCE_DATE) - 
               (CASE
                    WHEN SUBSTR(STUDENT_SSN, 1, 2) > TO_CHAR(SYSDATE, 'YY')
                    THEN 1900 + TO_NUMBER(SUBSTR(STUDENT_SSN, 1, 2))
                    ELSE 2000 + TO_NUMBER(SUBSTR(STUDENT_SSN, 1, 2))
               END)) AS 재수
    FROM TB_STUDENT
) 
WHERE 재수 > 19;

--6.
SELECT TO_CHAR(TO_DATE('20/12/25' , 'YY/MM/DD'), 'DAY') AS DAYNAME
FROM DUAL;

--7.
SELECT TO_CHAR(TO_DATE('99/10/11', 'YY/MM/DD'), 'YYYY/MM/DD') AS D1,
           TO_CHAR(TO_DATE('49/10/11', 'YY/MM/DD'), 'YYYY/MM/DD') AS D2,
           TO_CHAR(TO_DATE('99/10/11', 'RR/MM/DD'), 'YYYY/MM/DD') AS D3,
           TO_CHAR(TO_DATE('49/10/11', 'RR/MM/DD'), 'YYYY/MM/DD') AS D4
FROM DUAL;

--8.
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE SUBSTR(STUDENT_NO,1,1) != 'A';

--9.
SELECT ROUND(AVG(POINT),1) AS 평점
FROM TB_GRADE
JOIN TB_STUDENT USING(STUDENT_NO)
WHERE STUDENT_NO = 'A517178' AND STUDENT_NAME = '한아름';

--10.
SELECT DEPARTMENT_NO AS 학과번호 , COUNT(STUDENT_NO) AS "학생수(명)"
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO;

--11. 
SELECT COUNT(*)
FROM TB_STUDENT
WHERE COACH_PROFESSOR_NO IS NULL;

--12.
SELECT TERM_NO AS 년도, ROUND(POINT,1) AS "년도 별 평점"
FROM TB_GRADE
JOIN TB_STUDENT USING(STUDENT_NO)
WHERE STUDENT_NO = 'A112113' AND STUDENT_NAME = '김고운';

--13.
SELECT DEPARTMENT_NO AS 학과코드명, COUNT(ABSENCE_YN) AS "휴학생 수"
FROM TB_STUDENT
WHERE ABSENCE_YN = 'Y'
GROUP BY DEPARTMENT_NO;

--14.
SELECT DISTINCT(STUDENT_NAME) AS 동일이름, COUNT(*) AS "동명인 수"
FROM TB_STUDENT
GROUP BY STUDENT_NAME
HAVING COUNT(*) >1;

--15.
SELECT EXTRACT(YEAR FROM TO_DATE(TERM_NO,'YYYYMM')) AS 년도,
       CASE
            WHEN EXTRACT(MONTH FROM TO_DATE(TERM_NO, 'YYYYMM')) = 1 THEN 1
            WHEN EXTRACT(MONTH FROM TO_DATE(TERM_NO, 'YYYYMM')) = 2 THEN 2
            ELSE NULL
       END AS 학기,
       ROUND(POINT,1) AS "평점"
FROM TB_GRADE
JOIN TB_STUDENT USING(STUDENT_NO)
WHERE STUDENT_NO = 'A112113' AND STUDENT_NAME = '김고운'













