--1.
SELECT STUDENT_NAME AS "학생 이름", STUDENT_ADDRESS AS 주소지
FROM TB_STUDENT
ORDER BY STUDENT_NAME;

--2.
SELECT STUDENT_NAME, STUDENT_SSN
FROM TB_STUDENT
WHERE ABSENCE_YN = 'Y';

--3.
SELECT STUDENT_NAME AS 학생이름, STUDENT_NO AS 학번, STUDENT_ADDRESS AS "거주지 주소"
FROM TB_STUDENT
ORDER BY STUDENT_NAME;

--4.
SELECT PROFESSOR_NAME , PROFESSOR_SSN
FROM TB_PROFESSOR
ORDER BY PROFESSOR_SSN;

--5.
SELECT STUDENT_NO , POINT
FROM TB_GRADE
WHERE  TERM_NO = '200402'
ORDER BY POINT DESC;

--6.
SELECT STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
ORDER BY STUDENT_NAME;

--7.
SELECT CLASS_NAME, DEPARTMENT_NAME
FROM TB_CLASS
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO);

--8.
SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_CLASS
JOIN TB_PROFESSOR USING (DEPARTMENT_NO);

--9.
SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_CLASS
JOIN TB_PROFESSOR USING (DEPARTMENT_NO)
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE CATEGORY = '인문사회';

--10.
SELECT STUDENT_NO AS 학번,
            STUDENT_NAME AS "학생 이름",
            ROUND(AVG(POINT),1) AS "전체 평점"
FROM TB_STUDENT
JOIN TB_GRADE USING (STUDENT_NO)
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '음악학과'
GROUP BY STUDENT_NO, STUDENT_NAME;

--11.
SELECT DEPARTMENT_NAME AS 학과이름,
            STUDENT_NAME AS 학생이름, 
            PROFESSOR_NAME AS 지도교수이름
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
JOIN TB_PROFESSOR ON (PROFESSOR_NO = COACH_PROFESSOR_NO)
WHERE STUDENT_NO = 'A313047';

--12.
SELECT STUDENT_NAME, TERM_NO
FROM TB_STUDENT
JOIN TB_GRADE USING (STUDENT_NO)
JOIN TB_CLASS USING (DEPARTMENT_NO)
WHERE TERM_NO LIKE '2007%' AND CLASS_NAME = '인간관계론';

--13.
SELECT CLASS_NAME, DEPARTMENT_NAME
FROM TB_DEPARTMENT
JOIN TB_CLASS USING(DEPARTMENT_NO)
WHERE CATEGORY = '예체능' AND PREATTENDING_CLASS_NO IS NULL;

--14.
SELECT STUDENT_NAME AS 학생이름, NVL(PROFESSOR_NAME, '지도교수 미지정') AS 지도교수
FROM TB_STUDENT
LEFT JOIN TB_PROFESSOR ON(PROFESSOR_NO = COACH_PROFESSOR_NO)
ORDER BY STUDENT_NO DESC;

--15.
SELECT STUDENT_NO AS 학번, 
            STUDENT_NAME AS 이름, 
            DEPARTMENT_NAME AS "학과 이름",
            ROUND(AVG(POINT),1) AS 평점
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
JOIN TB_GRADE USING(STUDENT_NO)
WHERE ABSENCE_YN = 'N'
GROUP BY STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME
HAVING AVG(POINT) >=4.0
ORDER BY 평점;

--16.
SELECT CLASS_NO, CLASS_NAME, AVG(POINT)
FROM TB_CLASS
JOIN TB_GRADE USING(CLASS_NO)
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '환경조경학과'
GROUP BY CLASS_NO, CLASS_NAME;

--17.
SELECT STUDENT_NAME, STUDENT_ADDRESS
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = (
        SELECT DEPARTMENT_NAME
        FROM TB_STUDENT
        JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
        WHERE STUDENT_NAME = '최경희'
        );

--18.
SELECT *
FROM (
    SELECT ROWNUM AS RN, STUDENT_NO, STUDENT_NAME
    FROM (
        SELECT STUDENT_NO, STUDENT_NAME, AVG(POINT) AS AVG_POINT
        FROM TB_STUDENT
        JOIN TB_GRADE USING (STUDENT_NO)
        JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
        WHERE DEPARTMENT_NAME = '국어국문학과'
        GROUP BY STUDENT_NO, STUDENT_NAME
        ORDER BY AVG(POINT) DESC
    )
) 
WHERE RN = 1;



--19.
SELECT DEPARTMENT_NAME AS "계열 학과명", ROUND(AVG(POINT),1) AS "전공평점"
FROM TB_DEPARTMENT
JOIN TB_STUDENT USING(DEPARTMENT_NO)
JOIN TB_GRADE USING (STUDENT_NO)
GROUP BY DEPARTMENT_NAME;












