--1.
SELECT * FROM TB_CLASS_TYPE;

INSERT ALL
    INTO TB_CLASS_TYPE (PK_CLASS_TYPE_NO, CLASS_TYPE_NAME) VALUES (01, '전공필수')
    INTO TB_CLASS_TYPE (PK_CLASS_TYPE_NO, CLASS_TYPE_NAME) VALUES (02, '전공선택')
    INTO TB_CLASS_TYPE (PK_CLASS_TYPE_NO, CLASS_TYPE_NAME) VALUES (03, '교양필수')
    INTO TB_CLASS_TYPE (PK_CLASS_TYPE_NO, CLASS_TYPE_NAME) VALUES (04, '교양선택')
    INTO TB_CLASS_TYPE (PK_CLASS_TYPE_NO, CLASS_TYPE_NAME) VALUES (05, '논문지도')
SELECT * FROM DUAL;

--2.
CREATE TABLE TB_학생일반정보(
    학번 VARCHAR2(10) PRIMARY KEY,
    학생이름 VARCHAR2(40),
    주소 VARCHAR2(200)
);

INSERT INTO TB_학생일반정보(학번, 학생이름, 주소)
SELECT STUDENT_NO,
       STUDENT_NAME,
       STUDENT_ADDRESS
FROM TB_STUDENT;

--3.
CREATE TABLE TB_국어국문학과(
    학번 VARCHAR2(10) PRIMARY KEY,
    학생이름 VARCHAR2(40),
    출생년도 NUMBER(4),
    교수이름 VARCHAR2(40)
);


INSERT INTO TB_국어국문학과(학번, 학생이름, 출생년도, 교수이름)
SELECT STUDENT_NO,
       STUDENT_NAME,
       TO_NUMBER(SUBSTR(STUDENT_SSN,1,4))
       PROFESSOR_NAME
FROM TB_STUDENT
JOIN TB_PROFESSOR USING(DEPARTMENT_NO);
--잘 모르겠습니다.

--4.
UPDATE TB_DEPARTMENT
SET CAPACITY = ROUND(CAPACITY *1.1);

--5.
UPDATE TB_STUDENT
SET STUDENT_ADDRESS ='서울시 종로구 숭인동 181-21'
WHERE STUDENT_NO = 'A413042';

--6.
UPDATE TB_STUDENT
SET STUDENT_SSN = SUBSTR(STUDENT_SNN,1,7);

--7.
UPDATE TB_GRADE
SET POINT =3.5
WHERE STUDENT_NAME= '김명훈' AND CLASS_NAME = '피부생리학';

--8.
DELETE TB_GRADE
WHERE STUDENT_NO IN (
    SELECT STUDENT_NO
    FROM TB_STUDENT
    WHERE ABSENCE_YN = 'Y'
);











